// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:dailycore/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveAdapter());
    registerAdapter(ExpenseCategoryHiveAdapter());
    registerAdapter(ExpenseHiveAdapter());
    registerAdapter(GoalHiveAdapter());
    registerAdapter(HabitHiveAdapter());
    registerAdapter(TodoCategoryHiveAdapter());
    registerAdapter(TodoHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveAdapter());
    registerAdapter(ExpenseCategoryHiveAdapter());
    registerAdapter(ExpenseHiveAdapter());
    registerAdapter(GoalHiveAdapter());
    registerAdapter(HabitHiveAdapter());
    registerAdapter(TodoCategoryHiveAdapter());
    registerAdapter(TodoHiveAdapter());
  }
}
